### ISSUE TITLE
Can we customize or hide the Please Wait message when loading charts?

### ISSUE THREAD

**Issue by normancarcamo** [senthilnasa/high_chart#1]
I would like to remove the `Please Wait` message when the chart is loading, in my use case is not needed, is there a way to get this working without touching the source code from cache?

**Comment by senthilnasa** [comment]
Sorry  Normancarcamo  I have Not Provided option for that I will try provide the option as son as possible
Thank you for your Support

**Comment by senthilnasa** [comment]
Hi @normancarcamo,
I have added an option to provide a Custom loader 

Example 
```dart
# Pass Loader As Widget using loader Feild 
 HighCharts(
        loader: const SizedBox(
          child: LinearProgressIndicator(),
          width: 200,
        ),
        size: const Size(400, 400),
        data: '''    // data string''',
        scripts: const [
          "https://code.highcharts.com/highcharts.js",
          'https://code.highcharts.com/modules/networkgraph.js',
          'https://code.highcharts.com/modules/exporting.js',
        ],
      ),
    );
```

Thanks for using the Package.
