### ISSUE TITLE
Use local JS files

### ISSUE THREAD

**Issue by cargill-artuvic** [senthilnasa/high_chart#10]
How can I use high charts JS files locally? I tried adding the files in my project folder and in my assets in `pubspec.yaml` then I tried: 

    return Scaffold(
        ...
        body: HighCharts(
            ...
            scripts: const [
                'high_chart/accessibility.js',
        ...

But it did not work

**Comment by senthilnasa** [comment]
Hi @cargill-artuvic 

This will work only on the Web.

But on android and IoS, we are using WebView, so it will not work.

**Comment by Tombstone2K** [comment]
Is there any way that local js files support can be added. It seems like the only major thing missing right now

**Comment by azazadev** [comment]
Hi @senthilnasa  any plan to make it possible ?
