### ISSUE TITLE
Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=packedbubble

### ISSUE THREAD

**Issue by danwe** [senthilnasa/high_chart#11]
hi, i want to usage bubble in flutter.
i get this error, i read this error to be with this pack with angular10
how i can to usage bubble in flutter?
thank you

**Comment by cargill-artuvic** [comment]
You could try adding ` 'https://code.highcharts.com/highcharts-more.js',` to your scripts. So like:

    ...
    scripts: const [
          'https://code.highcharts.com/highcharts-more.js',
          'https://code.highcharts.com/highcharts.js',
          'https://code.highcharts.com/modules/networkgraph.js',
          'https://code.highcharts.com/modules/exporting.js',
          'https://code.highcharts.com/modules/accessibility.js',
        ],
    ...

However, it seems like my Flutter app is not able to retrieve the module anyway... It was working last week for me

**Comment by estergo** [comment]
Hi,

I also get the same problem when trying to use a simple bubble chart, even after adding `highcharts-more` script.
Does high_chart supports those graphs? Is this a issue? What can I do in order to make this working?

Thanks.

**Comment by cargill-artuvic** [comment]
It was working for me some weeks ago. I'm not sure why it suddenly stopped working. I actually can retrieve the files by other means such as on my machine and inside the emulator's browser
