### ISSUE TITLE
the size did not usefull    最新版本的在设置的size后在不起作用，如果height太小，就会遮挡底部

### ISSUE THREAD

**Issue by yuxingmin** [senthilnasa/high_chart#12]
child: HighCharts(
        loader: const SizedBox(
          child: LinearProgressIndicator(),
          width: 200,
        ),
        size: const Size(400, 380),
        data: logic.chartPption,
        scripts: const [
          "https://code.highcharts.com/highcharts.js",
          'https://code.highcharts.com/modules/networkgraph.js',
          'https://code.highcharts.com/modules/exporting.js',
        ],
      ),

**Comment by senthilnasa** [comment]
Hello yuxingmin,

Can you Share a Screenshot so it would be great to fix it out.
