### ISSUE TITLE
Kotlin Gradle plugin version needs to be updated

### ISSUE THREAD

**Issue by billyz313** [senthilnasa/high_chart#17]
I tried adding high_chart and got this error:

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':high_chart' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by Tombstone2K** [comment]
It has been upgraded, but the same is not reflected in pub.dev.

Although the issue should be addressed immediately, in the mean time as a workaround you can download the repository and add it to the pubspec.yaml file as a local repo, it works fine.

Like this under dependencies-> 
  high_chart:
    path: C:\Users\_username_\StudioProjects\packages\high_chart-master

**Comment by senthilnasa** [comment]
Hello,

First, I'd like to apologize for the delayed reply. We value your patience and support.

I'm pleased to inform you that we have fixed the issue with the high_chart package. To benefit from the resolved issue, please update your high_chart page to the latest version. This update includes the necessary fixes and improvements.

You can update to the latest version by adjusting your project's dependency configuration. If you need any assistance during the update process, feel free to reach out.

Thank you for your understanding and continued support.

Best regards,
Senthil Prabhu K

**Comment by ebala96** [comment]
Using high_chart: ^2.1.0 but still getting the above error.
