### ISSUE TITLE
Discrepancy between GitHub and pub.dev?

### ISSUE THREAD

**Issue by nurikabe** [senthilnasa/high_chart#19]
Quick question about pub.dev.. It shows the latest version as 2.0.3 published 14 months ago:

https://pub.dev/packages/high_chart/changelog

However the latest release on GitHub is 2.0.2:

https://github.com/senthilnasa/high_chart/releases

Is pub.dev pointing 2.0.3 to master or something like this?

Thanks so much for this library!

**Comment by senthilnasa** [comment]
Hello @nurikabe ,

My apologies for the delayed response, and thank you for your patience.

I'm pleased to inform you that the discrepancy has been resolved. Both pub.dev and GitHub now reflect the same version for the high_chart package. You can confidently use the latest version, knowing it's fully synchronized across both platforms.

Thank you for bringing this to our attention and for your support of the high_chart library.

Best regards,
Senthil Prabhu K
