### ISSUE TITLE
Any plans to support Web?

### ISSUE THREAD

**Issue by JardarM** [senthilnasa/high_chart#2]

**Comment by senthilnasa** [comment]
yes I am working on it

**Comment by m2faridi** [comment]
please support windows and mac

**Comment by senthilnasa** [comment]
ok I will look into  @m2faridi

**Comment by senthilnasa** [comment]
Hi @JardarM ,
We have Added Web Support to[ Latest of High Chart ](https://pub.dev/packages/high_chart)

Thanks for using the Package.
