### ISSUE TITLE
Please update the webview_flutter to lastVersion 4.2.4

### ISSUE THREAD

**Issue by yuxingmin** [senthilnasa/high_chart#22]
please！please！please！

**Comment by senthilnasa** [comment]
Thanks for using our package, 

Sure @yuxingmin, we are working on it

**Comment by mahmodmasoud2009** [comment]
Hello @senthilnasa  
Please update the webview package to new version:

webview_flutter: ^4.2.2

Thanks

**Comment by mahmodmasoud2009** [comment]
@yuxingmin 
try this demo 
https://github.com/kattaliraees/flutter_highchart

**Comment by senthilnasa** [comment]
Hello @yuxingmin ,

My apologies for the delayed response. We've successfully updated the webview_flutter plugin to the latest version, 4.2.4, as of today. This update aims to enhance your development experience by incorporating the latest features and fixes. We appreciate your patience and value your feedback. Should you encounter any issues or have further queries regarding this update, please feel free to reach out. Your input is crucial in helping us improve and maintain the quality of our plugin.

Best regards,
Senthil Prabhu K
