### ISSUE TITLE
Not working for IOS

### ISSUE THREAD

**Issue by ashpals** [senthilnasa/high_chart#3]
Can you guide how to solve this error ? 
It works well on android but on IOS i'm getting this warning and blank screen comes.
**Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service**

**Comment by sababuvercetti** [comment]
Same issue here

**Comment by ferguquang** [comment]
me too, I added NSAllowsArbitraryLoads = true in Info.plist, but this error still exists. Hope you fix this erro. 
Thank you very much

**Comment by ferguquang** [comment]
> I found a solution: Copied source of this library and changed webview from flutter team to inappwebview. Full source:
> 
> ```
> import 'package:flutter/foundation.dart';
> import 'package:flutter/widgets.dart';
> import 'package:flutter_inappwebview/flutter_inappwebview.dart';
> 
> import '../../../presentation/utils/high_chart_script.dart';
> 
> class HighCharts extends StatefulWidget {
>   const HighCharts({
>     required this.data,
>     Key? key,
>   }) : super(key: key);
> 
>   final String data;
> 
>   @override
>   _HighChartsState createState() => _HighChartsState();
> }
> 
> const highChartHtml =
>     '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0" /></head><body><div id="chart"></div></body></html><script>function senthilnasa(a){ eval(a); return true;}</script></html>';
> 
> class _HighChartsState extends State<HighCharts> {
>   String? _currentData;
> 
>   InAppWebViewController? webViewController;
>   InAppWebViewGroupOptions options = InAppWebViewGroupOptions(
>       crossPlatform: InAppWebViewOptions(
>         useShouldOverrideUrlLoading: true,
>         mediaPlaybackRequiresUserGesture: false,
>       ),
>       android: AndroidInAppWebViewOptions(
>         useHybridComposition: true,
>       ),
>       ios: IOSInAppWebViewOptions(
>         allowsInlineMediaPlayback: true,
>       ));
> 
>   @override
>   void initState() {
>     super.initState();
>     _currentData = widget.data;
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return InAppWebView(
>       initialData: InAppWebViewInitialData(data: highChartHtml),
>       initialOptions: options,
>       key: GlobalKey(),
>       onWebViewCreated: (controller) {
>         webViewController = controller;
>       },
>       androidOnPermissionRequest: (controller, origin, resources) async {
>         return PermissionRequestResponse(
>             resources: resources,
>             action: PermissionRequestResponseAction.GRANT);
>       },
>       onLoadStop: (controller, url) async {
>         await controller.evaluateJavascript(source: '''
>       $highchartsScript
>         var a= senthilnasa(`Highcharts.chart('chart',
>         $_currentData
>         )`);
>     ''');
>       },
>     );
>   }
> }
> ```
> 
> You can for now disable the lib and import this file. @senthilnasa Thanks again for the great job, and please migrate to flutter_inappwebview. Have a nice day!

thanks you very much, it works for me ^^

**Comment by senthilnasa** [comment]
The Issue is fixed and pushed to the [Latest Version](https://pub.dev/packages/high_chart)

Thank For using the Package

**Comment by ramkgunturu12** [comment]
Still this is not working even I updated to the latest version in iOS it is saying unable to open url
