### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by akash-gaea** [senthilnasa/high_chart#35]
Because high_chart 2.1.0 depends on js ^0.7.0 and every version of flutter_inappwebview_web depends on js ^0.6.4, high_chart 2.1.0 is incompatible with flutter_inappwebview_web.

And because flutter_inappwebview >=6.0.0 depends on flutter_inappwebview_web ^1.0.8, high_chart 2.1.0 is incompatible with flutter_inappwebview >=6.0.0.

**Comment by yuxingmin** [comment]
添加可以解决：
dependency_overrides:
  js: ^0.7.1
