### ISSUE TITLE
How to use highchart modules?

### ISSUE THREAD

**Issue by w99910** [senthilnasa/high_chart#4]
Hello ... 
In JS, I have to enable **networkgraph** module in order to use **networkgraph** chart. 
In this package, is there a way to enable module like that? I have to use **networkgraph** chart in flutter. 
Thanks for your awesome package. 
Cheers!

**Comment by senthilnasa** [comment]
Hi @w99910 ,

I have been given the option to add Hight Module 

Example
```dart
HighCharts(
        loader: const SizedBox(
          child: LinearProgressIndicator(),
          width: 200,
        ),
        size: const Size(400, 400),
        data: _chartData,
        scripts: const [
          "https://code.highcharts.com/highcharts.js",
         # Pass the cdn of module you need . Get Cdn URL from https://code.highcharts.com/
        ],
      );
```
